In [9]:

'''for syntax in python array as ndarray '''
#1d
import numpy as ds
arr = ds.array([1,2,3,4,5])
print(arr)

import numpy as ds
arr = ds.array(96.32)
print(arr)

[1 2 3 4 5]
96.32


In [8]:
#2d array.
import numpy as ds
arr = ds.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
#3d with 2d array.
import numpy as ds
arr = ds.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [6]:
#3d in array.
import numpy as ds
arr = ds.array([[[1,2,3,5],[4,5,6,0]],[[1,2,3,5],[4,5,6,7]]])
print(arr)#

[[[1 2 3 5]
  [4 5 6 0]]

 [[1 2 3 5]
  [4 5 6 7]]]


In [5]:
'''numpy array provides the ndim attribute that return an integer that tells us how many dimension the array have.. '''
arr = ds.array([1,2,3,4,5])
b = ds.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
c = ds.array([[1,2,3],[4,5,6]])
d = ds.array(96.32)

print(b.ndim)
print(c.ndim)
print(d.ndim)
print(arr.ndim)

3
2
0
1


In [4]:
'''for identifying the 1d array position of element ......'''

import numpy as ds
arr = ds.array([1,2,3,4,5])
print(arr[2])
print(arr[0])
print(arr[3])

3
1
4


In [3]:
'''get addition of elements in array'''

import numpy as ds
arr = ds.array([1,2,3,4,5])
print(arr[2]+arr[0])



4


In [2]:
''' how to get access in 2d array '''
import numpy as ds
arr = ds.array([[1,2,3],[4,5,6]])
print(arr[1,2])

6


In [10]:
# slice element array
import numpy as ds
arr = ds.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5])


import numpy as ds
arr = ds.array([1,2,3,4,5,6,7,8,9])
print(arr[0:5])


import numpy as ds
arr = ds.array([1,2,3,4,5,6,7,8,9])
print(arr[6:])

#negative slice 
import numpy as ds
arr = ds.array([1,2,3,4,5,6,7,8,9])
print(arr[-7:])

#STEP COUNT
import numpy as ds
arr = ds.array([1,2,3,4,5,6,7,8,9])
print(arr[6:7:8])

import numpy as ds
arr = ds.array([1,2,3,4,5,6,7,8,9])
print(arr[::2])

[2 3 4 5]
[1 2 3 4 5]
[7 8 9]
[3 4 5 6 7 8 9]
[7]
[1 3 5 7 9]


In [16]:
#slicing of 2d 

import numpy as ds 
arr = ds.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr[1,1:4])

[7 8 9]


In [36]:
import numpy as ds 
arr = ds.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr[1,2])

import numpy as ds 
arr = ds.array([[1,2,3,4,5],[6,7,8,9,0]])
row_slice=arr[0:2:]
print(arr[0:2:])

arr = ds.array([[1,2,3,4,5],[6,7,8,9,0]])
col_slice=arr[:,1:3]
print(arr[:,1:3])


8
[[1 2 3 4 5]
 [6 7 8 9 0]]
[[2 3]
 [7 8]]
