In [1]:
#1

import numpy as np

bool_array = np.ones((3, 3), dtype=bool)
print(bool_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [3]:
#2
import numpy as np

# np.linspace(start, stop, num_of_samples)
arr = np.linspace(5, 50, 10)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [4]:
#3
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

print(my_array)
print(type(my_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
#4
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]

print(reversed_arr)

[5 4 3 2 1]


In [6]:
#5
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
